apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-cluster-kafka
  description: my-cluster-kafka
  annotations:
    kafka.apache.org/consumer-groups: my-cluster-kafka  # Kafka cluster consumer group
    backstage.io/kafka-cluster: my-cluster-kafka       # Reference to Kafka cluster
    kafka.apache.org/dashboard-urls: my-cluster-kafka/kafdrop-mid-server.apps.66a64ff6d70fa4001ee0caae.ocp.techzone.ibm.com
  tags:
    - kafka
    - consumer
  labels:
    environment: production
spec:
  type: service                         # Service or library
  lifecycle: production
  owner: my-team                        # Team responsible for the component
  system: my-system                     # Optional system
  providesApis:
    - kafka                             # If you expose APIs
