apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-kafka-cluster
  description: Kafka cluster used for various logs and audit purposes
  tags:
    - kafka
    - logs
    - audit
  annotations:
    backstage.io/kafka: "true"  # Enable Kafka plugin in Backstage
    kafka.apache.org/dashboard-url: "https://kafdrop-mid-server.apps.66a64ff6d70fa4001ee0caae.ocp.techzone.ibm.com"  # Kafdrop dashboard URL (HTTPS)
    kafka.apache.org/brokers: "my-cluster-kafka-0.my-cluster-kafka-brokers.kafka-servicenow.svc:9092,my-cluster-kafka-1.my-cluster-kafka-brokers.kafka-servicenow.svc:9092,my-cluster-kafka-2.my-cluster-kafka-brokers.kafka-servicenow.svc:9092"  # List of Kafka brokers
    kafka.apache.org/clusters: "my-cluster-kafka"  # Kafka cluster name
    monitoring.kafdrop/url: "https://kafdrop-mid-server.apps.66a64ff6d70fa4001ee0caae.ocp.techzone.ibm.com"  # Kafdrop monitoring URL
    backstage.io/techdocs-ref: url:https://your-docs-url  # Optional: Add your techdocs link
spec:
  type: service
  owner: my-team
  lifecycle: production
  providesApis:
    - kafka
  implementsApis:
    - kafka
  kafka:
    clusters:
      - name: my-cluster-kafka
        brokers:
          - "my-cluster-kafka-0.my-cluster-kafka-brokers.kafka-servicenow.svc:9092"
          - "my-cluster-kafka-1.my-cluster-kafka-brokers.kafka-servicenow.svc:9092"
          - "my-cluster-kafka-2.my-cluster-kafka-brokers.kafka-servicenow.svc:9092"
        ssl: true  # Set to true if your Kafka brokers use SSL
        sasl: {}  # No SASL (authentication) as you mentioned it's not needed
    topics:
      - name: TEST.LOGS.1.APPS
        consumerGroup: Combined Lag
      - name: TEST.LOGS.1.AUDIT
        consumerGroup: Combined Lag
