apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-cluster-kafka
  description: Kafka cluster used for various logs and audit purposes
  annotations:
    backstage.io/kafka: "true"
    kafka.apache.org/dashboard-url: "https://kafdrop-mid-server.apps.66a64ff6d70fa4001ee0caae.ocp.techzone.ibm.com"
    monitoring.kafdrop/url: "https://kafdrop-mid-server.apps.66a64ff6d70fa4001ee0caae.ocp.techzone.ibm.com"
spec:
  type: service
  owner: my-team
  lifecycle: production
