apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-cluster-kafka
  description: Kafka cluster
  tags:
    - kafka
    - logs
    - audit
  annotations:
    backstage.io/kafka: "true"
    kafka.apache.org/dashboard-url: "https://kafdrop-mid-server.apps.66a64ff6d70fa4001ee0caae.ocp.techzone.ibm.com"
    #kafka.apache.org/brokers: "my-cluster-kafka-0.my-cluster-kafka-brokers.kafka-servicenow.svc:9092,my-cluster-kafka-1.my-cluster-kafka-brokers.kafka-servicenow.svc:9092,my-cluster-kafka-2.my-cluster-kafka-brokers.kafka-servicenow.svc:9092"
    kafka.apache.org/clusters: "my-cluster-kafka"
    monitoring.kafdrop/url: "https://kafdrop-mid-server.apps.66a64ff6d70fa4001ee0caae.ocp.techzone.ibm.com"
    backstage.io/techdocs-ref: url:https://your-docs-url
spec:
  type: service
  owner: my-team
  lifecycle: production
  providesApis:
    - kafka
  implementsApis:
    - kafka
  kafka:
    clusters:
      - name: my-cluster-kafka
        brokers:
          - "my-cluster-kafka-0.my-cluster-kafka-brokers.kafka-servicenow.svc:9092"
          - "my-cluster-kafka-1.my-cluster-kafka-brokers.kafka-servicenow.svc:9092"
          - "my-cluster-kafka-2.my-cluster-kafka-brokers.kafka-servicenow.svc:9092"
        ssl: false
    topics:
      - name: TEST.LOGS.1.APPS
        consumerGroup: Combined Lag
      - name: TEST.LOGS.1.AUDIT
        consumerGroup: Combined Lag
